window.DUNGCU = [

  ["螺丝刀","luósīdāo","tua vít"],
  ["一字螺丝刀","yí zì luósīdāo","tua vít dẹt"],
  ["十字螺丝刀","shí zì luósīdāo","tua vít bake"],
  ["电动螺丝刀","diàndòng luósīdāo","tua vít điện"],
  ["气动螺丝刀","qìdòng luósīdāo","tua vít khí"],
  ["螺丝批","luósī pī","tua vít"],
  ["扳手","bānshǒu","cờ lê"],
  ["活动扳手","huódòng bānshǒu","mỏ lết"],
  ["开口扳手","kāikǒu bānshǒu","cờ lê hai đầu hở"],
  ["梅花扳手","méihuā bānshǒu","cờ lê vòng"],
  ["两用扳手","liǎngyòng bānshǒu","cờ lê hai đầu"],
  ["套筒扳手","tàotǒng bānshǒu","bộ tuýp"],
  ["套筒","tàotǒng","đầu tuýp"],
  ["棘轮扳手","jí lún bānshǒu","cần siết bánh cóc"],
  ["内六角扳手","nèi liùjiǎo bānshǒu","lục giác"],
  ["六角扳手","liùjiǎo bānshǒu","cờ lê lục giác"],
  ["扭力扳手","niǔlì bānshǒu","cờ lê lực"],
  ["管钳","guǎnqián","kìm ống"],
  ["水管钳","shuǐguǎn qián","kìm nước"],
  ["尖嘴钳","jiānzuǐ qián","kìm mũi nhọn"],
  ["斜口钳","xiékǒu qián","kìm cắt chéo"],
  ["钢丝钳","gāngsī qián","kìm điện"],
  ["剥线钳","bōxiàn qián","kìm tuốt dây"],
  ["压线钳","yāxiàn qián","kìm bấm cos"],
  ["卡簧钳","kǎhuáng qián","kìm phe"],
  ["大力钳","dàlì qián","kìm chết"],
  ["尖嘴钳","jiānzuǐ qián","kìm nhọn"],
  ["圆嘴钳","yuánzuǐ qián","kìm mũi tròn"],
  ["鸭嘴钳","yāzuǐ qián","kìm mỏ vịt"],
  ["电子钳","diànzǐ qián","kìm điện tử"],

  ["锤子","chuízi","búa"],
  ["铁锤","tiěchuí","búa sắt"],
  ["橡胶锤","xiàngjiāo chuí","búa cao su"],
  ["木锤","mùchuí","búa gỗ"],
  ["羊角锤","yángjiǎo chuí","búa nhổ đinh"],
  ["电工锤","diàngōng chuí","búa thợ điện"],
  ["凿子","záozi","đục"],
  ["冲子","chōngzi","đột"],
  ["冲头","chōngtóu","đầu đột"],
  ["钢锯","gāngjù","cưa sắt"],
  ["手锯","shǒujù","cưa tay"],
  ["锯条","jùtiáo","lưỡi cưa"],
  ["美工刀","měigōng dāo","dao rọc giấy"],
  ["刀片","dāopiàn","lưỡi dao"],
  ["剪刀","jiǎndāo","kéo"],
  ["铁剪","tiějiǎn","kéo cắt sắt"],
  ["剥线刀","bōxiàn dāo","dao tuốt dây"],
  ["电工刀","diàngōng dāo","dao thợ điện"],
  ["镊子","nièzi","nhíp"],
  ["镊子钳","nièzi qián","kìm nhíp"],

  ["电钻","diànzuàn","máy khoan điện"],
  ["手电钻","shǒu diànzuàn","khoan cầm tay"],
  ["冲击钻","chōngjī zuàn","máy khoan búa"],
  ["电锤","diànchuí","máy khoan đục"],
  ["角磨机","jiǎomó jī","máy mài góc"],
  ["砂轮机","shālún jī","máy mài"],
  ["切割机","qiēgē jī","máy cắt"],
  ["打磨机","dǎmó jī","máy đánh bóng/mài"],
  ["抛光机","pāoguāng jī","máy đánh bóng"],
  ["电磨","diànmó","máy mài mini"],
  ["热风枪","rèfēng qiāng","súng khò nhiệt"],
  ["吹风机","chuīfēngjī","máy thổi"],
  ["吸尘器","xīchénqì","máy hút bụi"],
  ["手电筒","shǒudiàntǒng","đèn pin"],
  ["充电器","chōngdiànqì","bộ sạc"],
  ["充电电钻","chōngdiàn diànzuàn","máy khoan pin"],
  ["电池","diànchí","pin"],
  ["电池盒","diànchí hé","hộp pin"],
  ["延长线","yáncháng xiàn","dây nối dài"],
  ["插线板","chāxiànbǎn","ổ cắm kéo dài"],

  ["万用表","wànyòngbiǎo","đồng hồ vạn năng"],
  ["数字万用表","shùzì wànyòngbiǎo","đồng hồ vạn năng số"],
  ["指针万用表","zhǐzhēn wànyòngbiǎo","đồng hồ vạn năng kim"],
  ["钳形表","qiánxíng biǎo","ampe kìm"],
  ["兆欧表","zhào'ōu biǎo","đồng hồ đo cách điện"],
  ["电压表","diànyā biǎo","vôn kế"],
  ["电流表","diànliú biǎo","ampe kế"],
  ["功率表","gōnglǜ biǎo","đồng hồ công suất"],
  ["频率表","pínlǜ biǎo","đồng hồ đo tần số"],
  ["示波器","shìbōqì","máy hiện sóng"],
  ["信号发生器","xìnhào fāshēngqì","máy phát tín hiệu"],
  ["直流电源","zhíliú diànyuán","nguồn DC"],
  ["稳压电源","wěnyā diànyuán","nguồn ổn áp"],
  ["可调电源","kětiáo diànyuán","nguồn điều chỉnh được"],
  ["测电笔","cèdiàn bǐ","bút thử điện"],
  ["验电笔","yàndiàn bǐ","bút thử điện"],
  ["电笔","diànbǐ","bút điện"],
  ["测温仪","cèwēn yí","máy đo nhiệt độ"],
  ["红外测温仪","hóngwài cèwēn yí","súng đo nhiệt độ hồng ngoại"],
  ["温度计","wēndùjì","nhiệt kế"],

  ["游标卡尺","yóubiāo kǎchǐ","thước cặp"],
  ["卡尺","kǎchǐ","thước cặp"],
  ["千分尺","qiānfēnchǐ","panme"],
  ["外径千分尺","wàijìng qiānfēnchǐ","panme đo ngoài"],
  ["内径千分尺","nèijìng qiānfēnchǐ","panme đo trong"],
  ["深度尺","shēndù chǐ","thước đo sâu"],
  ["钢尺","gāngchǐ","thước thép"],
  ["直尺","zhíchǐ","thước thẳng"],
  ["卷尺","juǎnchǐ","thước cuộn"],
  ["角尺","jiǎochǐ","thước vuông"],
  ["水平尺","shuǐpíng chǐ","thước thủy"],
  ["塞尺","sāichǐ","thước lá"],
  ["厚度规","hòudù guī","dưỡng đo độ dày"],
  ["半径规","bànjìng guī","dưỡng đo bán kính"],
  ["螺纹规","luówén guī","dưỡng ren"],
  ["间隙规","jiànxì guī","dưỡng khe hở"],
  ["量角器","liángjiǎoqì","thước đo góc"],
  ["水平仪","shuǐpíngyí","máy đo cân bằng"],
  ["激光水平仪","jīguāng shuǐpíngyí","máy cân bằng laser"],
  ["测距仪","cèjùyí","máy đo khoảng cách"],

  ["电烙铁","diànlàotiě","mỏ hàn điện"],
  ["烙铁头","làotiě tóu","đầu mỏ hàn"],
  ["焊台","hàntái","trạm hàn"],
  ["焊枪","hànqiāng","súng hàn"],
  ["吸锡器","xīxīqì","bơm hút thiếc"],
  ["吸锡带","xīxī dài","dây hút thiếc"],
  ["焊锡丝","hànxīsī","thiếc hàn dạng dây"],
  ["焊锡","hànxī","thiếc hàn"],
  ["助焊剂","zhùhànjì","flux / chất trợ hàn"],
  ["焊锡膏","hànxīgāo","kem hàn"],
  ["松香","sōngxiāng","nhựa thông"],
  ["热风焊台","rèfēng hàntái","trạm khò nhiệt"],
  ["镊子","nièzi","nhíp"],
  ["放大镜","fàngdàjìng","kính lúp"],
  ["显微镜","xiǎnwéijìng","kính hiển vi"],
  ["电子显微镜","diànzǐ xiǎnwéijìng","kính hiển vi điện tử"],
  ["工作灯","gōngzuò dēng","đèn làm việc"],
  ["台灯","táidēng","đèn bàn"],
  ["焊接夹","hànjiē jiā","kẹp hàn"],
  ["万向夹","wànxiàng jiā","kẹp đa năng"],

  ["钻头","zuàntóu","mũi khoan"],
  ["麻花钻头","máhuā zuàntóu","mũi khoan xoắn"],
  ["金刚石钻头","jīngāngshí zuàntóu","mũi khoan kim cương"],
  ["螺丝批头","luósī pītóu","đầu vít"],
  ["批头","pītóu","đầu vít"],
  ["六角批头","liùjiǎo pītóu","đầu vít lục giác"],
  ["套筒头","tàotǒng tóu","đầu tuýp"],
  ["磨片","mópiàn","đá mài"],
  ["切割片","qiēgē piàn","đĩa cắt"],
  ["砂纸","shāzhǐ","giấy nhám"],
  ["砂轮片","shālún piàn","đá/đĩa mài"],
  ["钢丝刷","gāngsī shuā","bàn chải sắt"],
  ["毛刷","máoshuā","chổi cọ"],
  ["刷子","shuāzi","bàn chải"],
  ["锉刀","cuòdāo","dũa"],
  ["什锦锉","shíjǐn cuò","bộ dũa kim"],
  ["三角锉","sānjiǎo cuò","dũa tam giác"],
  ["圆锉","yuáncuò","dũa tròn"],
  ["平锉","píngcuò","dũa dẹt"],
  ["半圆锉","bànyuán cuò","dũa bán nguyệt"],

  ["工作台","gōngzuòtái","bàn làm việc"],
  ["工具箱","gōngjùxiāng","hộp dụng cụ"],
  ["工具柜","gōngjù guì","tủ dụng cụ"],
  ["工具车","gōngjù chē","xe đẩy dụng cụ"],
  ["工具包","gōngjù bāo","túi dụng cụ"],
  ["零件盒","língjiàn hé","hộp linh kiện"],
  ["收纳盒","shōunà hé","hộp đựng"],
  ["工具架","gōngjù jià","giá dụng cụ"],
  ["扳手套装","bānshǒu tàozhuāng","bộ cờ lê"],
  ["工具套装","gōngjù tàozhuāng","bộ dụng cụ"],

  ["夹具","jiājù","đồ gá / jig"],
  ["治具","zhìjù","đồ gá / jig"],
  ["工装","gōngzhuāng","đồ gá / dụng cụ công nghệ"],
  ["台虎钳","tái hǔqián","ê tô bàn"],
  ["虎钳","hǔqián","ê tô"],
  ["夹钳","jiāqián","kìm kẹp"],
  ["C型夹","C xíng jiā","kẹp chữ C"],
  ["快速夹","kuàisù jiā","kẹp nhanh"],
  ["磁性表座","cíxìng biǎozuò","đế từ"],
  ["磁铁","cítiě","nam châm"],

  ["螺丝","luósī","ốc vít"],
  ["螺母","luómǔ","đai ốc"],
  ["垫片","diànpiàn","long đen"],
  ["弹簧垫片","tánhuáng diànpiàn","long đen vênh"],
  ["平垫片","píng diànpiàn","long đen phẳng"],
  ["弹簧","tánhuáng","lò xo"],
  ["销子","xiāozi","chốt"],
  ["定位销","dìngwèi xiāo","chốt định vị"],
  ["卡簧","kǎhuáng","phe"],
  ["轴承","zhóuchéng","vòng bi"],
  ["齿轮","chǐlún","bánh răng"],
  ["皮带","pídài","dây curoa"],
  ["链条","liàntiáo","xích"],
  ["链轮","liànlún","nhông xích"],
  ["联轴器","liánzhóuqì","khớp nối trục"],
  ["密封圈","mìfēngquān","gioăng / vòng đệm kín"],
  ["O型圈","O xíng quān","gioăng O-ring"],
  ["油封","yóufēng","phớt dầu"],
  ["润滑油","rùnhuá yóu","dầu bôi trơn"],
  ["黄油","huángyóu","mỡ bôi trơn"],

  ["油枪","yóuqiāng","súng bơm dầu/mỡ"],
  ["黄油枪","huángyóu qiāng","súng bơm mỡ"],
  ["漏斗","lòudǒu","phễu"],
  ["油壶","yóuhú","bình dầu"],
  ["喷壶","pēnhú","bình xịt"],
  ["喷枪","pēnqiāng","súng phun"],
  ["气枪","qìqiāng","súng khí"],
  ["气管","qìguǎn","ống khí"],
  ["气动工具","qìdòng gōngjù","dụng cụ khí nén"],
  ["气动扳手","qìdòng bānshǒu","súng siết khí"],
  ["气动打磨机","qìdòng dǎmó jī","máy mài khí"],
  ["气动剪","qìdòng jiǎn","kéo khí nén"],
  ["气泵","qìbèng","máy nén khí"],
  ["空压机","kōngyā jī","máy nén khí"],
  ["气缸","qìgāng","xi lanh khí"],
  ["压力表","yālì biǎo","đồng hồ áp suất"],
  ["调压阀","tiáoyā fá","van điều áp"],
  ["电磁阀","diàncí fá","van điện từ"],
  ["接头","jiētóu","đầu nối"],
  ["快速接头","kuàisù jiētóu","đầu nối nhanh"],

  ["扳手架","bānshǒu jià","giá cờ lê"],
  ["螺丝刀架","luósīdāo jià","giá tua vít"],
  ["防静电手环","fángjìngdiàn shǒuhuán","vòng tay chống tĩnh điện"],
  ["防静电垫","fángjìngdiàn diàn","thảm chống tĩnh điện"],
  ["防静电手套","fángjìngdiàn shǒutào","găng tay chống tĩnh điện"],
  ["绝缘手套","juéyuán shǒutào","găng tay cách điện"],
  ["绝缘工具","juéyuán gōngjù","dụng cụ cách điện"],
  ["安全眼镜","ānquán yǎnjìng","kính bảo hộ"],
  ["护目镜","hùmùjìng","kính bảo hộ mắt"],
  ["口罩","kǒuzhào","khẩu trang"],
  ["耳塞","ěrsāi","nút tai chống ồn"],
  ["安全帽","ānquánmào","mũ bảo hộ"],
  ["安全鞋","ānquán xié","giày bảo hộ"],
  ["手套","shǒutào","găng tay"],
  ["工具绳","gōngjù shéng","dây giữ dụng cụ"],
  ["安全带","ānquán dài","dây an toàn"],
  ["警示牌","jǐngshì pái","biển cảnh báo"],
  ["警示带","jǐngshì dài","dây cảnh báo"],
  ["照明灯","zhàomíng dēng","đèn chiếu sáng"],
  ["工作平台","gōngzuò píngtái","sàn/bục làm việc"]

];