window.EPNHUA = [
[“产品”,“chǎnpǐn”,“sản phẩm”],
[“注塑机”,“zhùsù jī”,“máy ép nhựa”],
[“模具”,“mújù”,“khuôn”],
[“不良”,“bùliáng”,“lỗi/không đạt”],
[“不良品”,“bùliángpǐn”,“sản phẩm lỗi”],
[“良品”,“liángpǐn”,“sản phẩm đạt”],
[“检查”,“jiǎnchá”,“kiểm tra”],
[“参数”,“cānshù”,“thông số”],
[“调整”,“tiáozhěng”,“điều chỉnh”],
[“温度”,“wēndù”,“nhiệt độ”],
[“压力”,“yālì”,“áp suất”],
[“速度”,“sùdù”,“tốc độ”],
[“生产”,“shēngchǎn”,“sản xuất”],
[“故障”,“gùzhàng”,“sự cố”],
[“报警”,“bàojǐng”,“báo động”],
[“维修”,“wéixiū”,“sửa chữa”],
[“原料”,“yuánliào”,“nguyên liệu”],
[“缺胶”,“quējiāo”,“thiếu nhựa”],
[“毛边”,“máobiān”,“ba via”],
[“缩水”,“suōshuǐ”,“co ngót/lõm”],
[“变形”,“biànxíng”,“biến dạng”],
[“翘曲”,“qiàoqū”,“cong vênh”],
[“黑点”,“hēidiǎn”,“điểm đen”],
[“色差”,“sèchā”,“lệch màu”],
[“刮伤”,“guāshāng”,“trầy xước”],
[“裂纹”,“lièwén”,“vết nứt”],
[“气泡”,“qìpào”,“bọt khí”],
[“银丝”,“yínsī”,“vệt bạc”],
[“烧焦”,“shāojiāo”,“cháy”],
[“流痕”,“liúhén”,“vết dòng chảy”],
[“熔接痕”,“róngjiē hén”,“đường hàn”],
[“顶针印”,“dǐngzhēn yìn”,“dấu chốt đẩy”],
[“粘模”,“zhānmó”,“dính khuôn”],
[“尺寸”,“chǐcùn”,“kích thước”],
[“公差”,“gōngchā”,“dung sai”],
[“外观”,“wàiguān”,“ngoại quan”],
[“射出”,“shèchū”,“phun”],
[“保压”,“bǎoyā”,“giữ áp”],
[“冷却”,“lěngquè”,“làm mát”],
[“塑化”,“sùhuà”,“hóa dẻo”],
[“螺杆”,“luógǎn”,“trục vít”],
[“背压”,“bèiyā”,“áp suất ngược”],
[“开模”,“kāimó”,“mở khuôn”],
[“合模”,“hémó”,“đóng khuôn”],
[“顶针”,“dǐngzhēn”,“chốt đẩy”],
[“水口”,“shuǐkǒu”,“cuống/cổng nhựa”],
[“热流道”,“rèliúdào”,“kênh nóng”],
[“喷嘴”,“pēnzuǐ”,“đầu phun”],
[“冷却水”,“lěngquè shuǐ”,“nước làm mát”],
[“模温”,“múwēn”,“nhiệt độ khuôn”],
[“料温”,“liàowēn”,“nhiệt độ liệu”],
[“保压时间”,“bǎoyā shíjiān”,“thời gian giữ áp”],
[“射出速度”,“shèchū sùdù”,“tốc độ phun”],
[“射出压力”,“shèchū yālì”,“áp suất phun”],
[“冷却时间”,“lěngquè shíjiān”,“thời gian làm mát”],
[“周期”,“zhōuqī”,“chu kỳ”],
[“成型”,“chéngxíng”,“tạo hình/ép thành phẩm”],
[“成型周期”,“chéngxíng zhōuqī”,“chu kỳ ép”],
[“机器”,“jīqì”,“máy móc”],
[“机台”,“jītái”,“máy/máy ép”],
[“开机”,“kāijī”,“mở máy”],
[“关机”,“guānjī”,“tắt máy”],
[“停机”,“tíngjī”,“dừng máy”],
[“启动”,“qǐdòng”,“khởi động”],
[“停止”,“tíngzhǐ”,“dừng”],
[“自动”,“zìdòng”,“tự động”],
[“手动”,“shǒudòng”,“thủ công”],
[“半自动”,“bàn zìdòng”,“bán tự động”],
[“设置”,“shèzhì”,“cài đặt”],
[“设定”,“shèdìng”,“thiết lập/cài đặt”],
[“实际”,“shíjì”,“thực tế”],
[“设定值”,“shèdìng zhí”,“giá trị cài đặt”],
[“实际值”,“shíjì zhí”,“giá trị thực tế”],
[“检测”,“jiǎncè”,“kiểm tra/phát hiện”],
[“测量”,“cèliáng”,“đo”],
[“确认”,“quèrèn”,“xác nhận”],
[“判断”,“pànduàn”,“phán đoán”],
[“原因”,“yuányīn”,“nguyên nhân”],
[“问题”,“wèntí”,“vấn đề”],
[“处理”,“chǔlǐ”,“xử lý”],
[“改善”,“gǎishàn”,“cải thiện”],
[“调机”,“tiáojī”,“chỉnh máy”],
[“调试”,“tiáoshì”,“chạy thử/điều chỉnh”],
[“重新”,“chóngxīn”,“lại/lại một lần nữa”],
[“更换”,“gēnghuàn”,“thay thế”],
[“清理”,“qīnglǐ”,“làm sạch/dọn”],
[“清洁”,“qīngjié”,“vệ sinh”],
[“保养”,“bǎoyǎng”,“bảo dưỡng”],
[“正常”,“zhèngcháng”,“bình thường”],
[“异常”,“yìcháng”,“bất thường”],
[“严重”,“yánzhòng”,“nghiêm trọng”],
[“轻微”,“qīngwēi”,“nhẹ”],
[“过高”,“guò gāo”,“quá cao”],
[“过低”,“guò dī”,“quá thấp”],
[“不够”,“búgòu”,“không đủ”],
[“太大”,“tài dà”,“quá lớn”],
[“太小”,“tài xiǎo”,“quá nhỏ”],
[“太快”,“tài kuài”,“quá nhanh”],
[“太慢”,“tài màn”,“quá chậm”],
[“稳定”,“wěndìng”,“ổn định”],
[“料斗”,“liàodǒu”,“phễu liệu”],
[“颗粒”,“kēlì”,“hạt nhựa”],
[“色母”,“sèmǔ”,“hạt màu”],
[“配料”,“pèiliào”,“phối liệu”],
[“混料”,“hùnliào”,“trộn liệu”],
[“加料”,“jiāliào”,“cấp liệu”],
[“送料”,“sòngliào”,“cấp/đưa liệu”],
[“缺料”,“quēliào”,“thiếu liệu”],
[“堵料”,“dǔliào”,“nghẹt liệu”],
[“烘料”,“hōngliào”,“sấy liệu”],
[“干燥”,“gānzào”,“làm khô/sấy”],
[“干燥机”,“gānzào jī”,“máy sấy”],
[“吸料机”,“xīliào jī”,“máy hút liệu”],
[“料管”,“liàoguǎn”,“ống liệu”],
[“熔胶”,“róngjiāo”,“nhựa nóng chảy”],
[“熔胶量”,“róngjiāo liàng”,“lượng nhựa hóa dẻo”],
[“加热”,“jiārè”,“gia nhiệt”],
[“加热圈”,“jiārè quān”,“vòng gia nhiệt”],
[“热电偶”,“rèdiàn’ǒu”,“cặp nhiệt điện”],
[“温控”,“wēnkòng”,“điều khiển nhiệt”],
[“模腔”,“múqiāng”,“lòng khuôn”],
[“型芯”,“xíngxīn”,“lõi khuôn”],
[“滑块”,“huákuài”,“slider”],
[“斜顶”,“xiédǐng”,“ty/lõi xiên”],
[“镶件”,“xiāngjiàn”,“insert”],
[“排气”,“páiqì”,“thoát khí”],
[“排气槽”,“páiqì cáo”,“rãnh thoát khí”],
[“水路”,“shuǐlù”,“đường nước”],
[“水管”,“shuǐguǎn”,“ống nước”],
[“水温”,“shuǐwēn”,“nhiệt độ nước”],
[“漏水”,“lòushuǐ”,“rò nước”],
[“漏胶”,“lòujiāo”,“rò nhựa”],
[“堵塞”,“dǔsè”,“tắc nghẽn”],
[“堵嘴”,“dǔzuǐ”,“nghẹt đầu phun”],
[“粘胶”,“zhānjiāo”,“dính nhựa”],
[“脱模”,“tuōmó”,“tháo khuôn”],
[“脱模不良”,“tuōmó bùliáng”,“tháo khuôn không tốt”],
[“顶出”,“dǐngchū”,“đẩy sản phẩm”],
[“顶出不良”,“dǐngchū bùliáng”,“đẩy sản phẩm không tốt”],
[“卡模”,“kǎmó”,“kẹt khuôn”],
[“变色”,“biànsè”,“đổi màu”],
[“色不均”,“sè bù jūn”,“màu không đều”],
[“银纹”,“yínwén”,“vân bạc”],
[“气纹”,“qìwén”,“vết khí”],
[“气痕”,“qìhén”,“dấu khí”],
[“波纹”,“bōwén”,“vân sóng”],
[“缩痕”,“suōhén”,“vết co”],
[“凹痕”,“āohén”,“vết lõm”],
[“白印”,“báiyìn”,“vết trắng”],
[“白化”,“báihuà”,“trắng hóa”],
[“顶白”,“dǐngbái”,“trắng do chốt đẩy”],
[“黑印”,“hēiyìn”,“vết đen”],
[“油污”,“yóuwū”,“vết dầu”],
[“污渍”,“wūzì”,“vết bẩn”],
[“灰尘”,“huīchén”,“bụi”],
[“毛刺”,“máocì”,“gờ sắc/ba via”],
[“缺口”,“quēkǒu”,“mẻ/khuyết”],
[“破损”,“pòsǔn”,“hư hỏng”],
[“碰伤”,“pèngshāng”,“vết va đập”],
[“压伤”,“yāshāng”,“vết ép”],
[“断裂”,“duànliè”,“gãy”],
[“开裂”,“kāiliè”,“nứt”],
[“粘模”,“zhānmó”,“dính khuôn”],
[“飞边”,“fēibiān”,“ba via”],
[“溢胶”,“yìjiāo”,“tràn nhựa”],
[“短射”,“duǎnshè”,“short shot/thiếu nhựa”],
[“填充不足”,“tiánchōng bùzú”,“điền đầy không đủ”],
[“喷射纹”,“pēnshè wén”,“vết phun tia”],
[“气泡”,“qìpào”,“bọt khí”],
[“烧焦纹”,“shāojiāo wén”,“vết cháy”],
[“机械手”,“jīxièshǒu”,“tay máy”],
[“取件”,“qǔjiàn”,“lấy sản phẩm”],
[“输送带”,“shūsòngdài”,“băng tải”],
[“夹具”,“jiājù”,“đồ gá/kẹp”],
[“计数”,“jìshù”,“đếm”],
[“数量”,“shùliàng”,“số lượng”],
[“批次”,“pīcì”,“lô hàng”],
[“型号”,“xínghào”,“mã/model”],
[“规格”,“guīgé”,“quy cách”],
[“样品”,“yàngpǐn”,“mẫu”],
[“首件”,“shǒujiàn”,“sản phẩm đầu tiên”],
[“首件确认”,“shǒujiàn quèrèn”,“xác nhận sản phẩm đầu”],
[“抽检”,“chōujiǎn”,“kiểm tra lấy mẫu”],
[“全检”,“quánjiǎn”,“kiểm tra 100%”],
[“返工”,“fǎngōng”,“làm lại”],
[“报废”,“bàofèi”,“loại bỏ/phế”],
[“返修”,“fǎnxiū”,“sửa lại”],
[“隔离”,“gélí”,“cách ly hàng lỗi”],
[“标识”,“biāoshí”,“nhận diện/đánh dấu”],
[“品质”,“pǐnzhì”,“chất lượng”],
[“品管”,“pǐnguǎn”,“quản lý chất lượng”],
[“质量”,“zhìliàng”,“chất lượng”],
[“标准”,“biāozhǔn”,“tiêu chuẩn”],
[“要求”,“yāoqiú”,“yêu cầu”],
[“记录”,“jìlù”,“ghi chép”],
[“数据”,“shùjù”,“dữ liệu”],
[“原因分析”,“yuányīn fēnxī”,“phân tích nguyên nhân”],
[“改善措施”,“gǎishàn cuòshī”,“biện pháp cải thiện”],
[“再确认”,“zài quèrèn”,“xác nhận lại”],
[“继续生产”,“jìxù shēngchǎn”,“tiếp tục sản xuất”]
];