const HSK1 = [
  ["爱","ài","yêu; thích"],
  ["八","bā","tám"],
  ["爸爸","bàba","bố; cha"],
  ["吧","ba","trợ từ"],
  ["白天","báitiān","ban ngày"],
  ["百","bǎi","trăm"],
  ["半","bàn","một nửa"],
  ["包子","bāozi","bánh bao"],
  ["杯子","bēizi","cốc; ly"],
  ["本","běn","quyển; cuốn"],
  ["边","biān","bên; phía"],
  ["病","bìng","bệnh; ốm"],
  ["不","bù","không"],
  ["不客气","bú kèqi","không có gì"],
  ["不要","bú yào","đừng; không muốn"],
  ["菜","cài","rau; món ăn"],
  ["茶","chá","trà"],
  ["唱","chàng","hát"],
  ["超市","chāoshì","siêu thị"],
  ["车","chē","xe"],
  ["吃","chī","ăn"],
  ["出租车","chūzūchē","taxi"],
  ["穿","chuān","mặc"],
  ["打电话","dǎ diànhuà","gọi điện thoại"],
  ["大","dà","to; lớn"],
  ["大家","dàjiā","mọi người"],
  ["大学","dàxué","đại học"],
  ["大学生","dàxuéshēng","sinh viên"],
  ["到","dào","đến; tới"],
  ["的","de","trợ từ"],
  ["第","dì","thứ; tiền tố số thứ tự"],
  ["弟弟","dìdi","em trai"],
  ["点","diǎn","giờ; điểm; chút"],
  ["店","diàn","cửa hàng"],
  ["电话","diànhuà","điện thoại"],
  ["电脑","diànnǎo","máy tính"],
  ["电视","diànshì","tivi"],
  ["电影","diànyǐng","phim"],
  ["电影院","diànyǐngyuàn","rạp chiếu phim"],
  ["东西","dōngxi","đồ vật"],
  ["都","dōu","đều"],
  ["读","dú","đọc"],
  ["读书","dúshū","đọc sách; học"],
  ["对","duì","đúng; đối với"],
  ["对不起","duìbuqǐ","xin lỗi"],
  ["多","duō","nhiều"],
  ["多少","duōshao","bao nhiêu"],
  ["儿子","érzi","con trai"],
  ["二","èr","hai"],
  ["饭","fàn","cơm; bữa ăn"],
  ["饭店","fàndiàn","nhà hàng"],
  ["房间","fángjiān","phòng"],
  ["非常","fēicháng","rất; vô cùng"],
  ["飞机","fēijī","máy bay"],
  ["分","fēn","phút; phần"],
  ["分钟","fēnzhōng","phút"],
  ["高兴","gāoxìng","vui; vui vẻ"],
  ["歌","gē","bài hát"],
  ["哥哥","gēge","anh trai"],
  ["个","gè","lượng từ"],
  ["给","gěi","cho; đưa cho"],
  ["公司","gōngsī","công ty"],
  ["工作","gōngzuò","công việc; làm việc"],
  ["狗","gǒu","chó"],
  ["贵","guì","đắt"],
  ["国","guó","nước; quốc gia"],
  ["还","hái","vẫn; còn"],
  ["孩子","háizi","đứa trẻ; con"],
  ["汉语","Hànyǔ","tiếng Hán"],
  ["汉字","Hànzì","chữ Hán"],
  ["好","hǎo","tốt"],
  ["好吃","hǎochī","ngon"],
  ["好看","hǎokàn","đẹp; đẹp mắt"],
  ["好听","hǎotīng","hay; dễ nghe"],
  ["好玩儿","hǎowánr","vui; thú vị"],
  ["号","hào","số; ngày"],
  ["喝","hē","uống"],
  ["和","hé","và; với"],
  ["很","hěn","rất"],
  ["后","hòu","sau; phía sau"],
  ["回","huí","về; quay lại"],
  ["会","huì","biết; có thể"],
  ["火车","huǒchē","tàu hỏa"],
  ["鸡蛋","jīdàn","trứng gà"],
  ["几","jǐ","mấy; bao nhiêu"],
  ["家","jiā","nhà; gia đình"],
  ["家人","jiārén","người nhà; gia đình"],
  ["见","jiàn","gặp; thấy"],
  ["件","jiàn","lượng từ cho quần áo/sự việc"],
  ["饺子","jiǎozi","bánh chẻo"],
  ["叫","jiào","gọi; tên là"],
  ["姐姐","jiějie","chị gái"],
  ["今年","jīnnián","năm nay"],
  ["今天","jīntiān","hôm nay"],
  ["九","jiǔ","chín"],
  ["觉得","juéde","cảm thấy; cho rằng"],
  ["开","kāi","mở; lái"],
  ["开车","kāichē","lái xe"],
  ["看","kàn","xem; nhìn"],
  ["看病","kànbìng","khám bệnh"],
  ["看见","kànjiàn","nhìn thấy"],
  ["可以","kěyǐ","có thể; được"],
  ["课","kè","bài học; tiết học"],
  ["口","kǒu","miệng; lượng từ người"],
  ["块","kuài","miếng; đồng"],
  ["来","lái","đến"],
  ["老师","lǎoshī","giáo viên"],
  ["了","le","trợ từ"],
  ["冷","lěng","lạnh"],
  ["里","lǐ","trong; bên trong"],
  ["两","liǎng","hai"],
  ["零","líng","số không"],
  ["六","liù","sáu"],
  ["妈妈","māma","mẹ"],
  ["吗","ma","trợ từ nghi vấn"],
  ["买","mǎi","mua"],
  ["卖","mài","bán"],
  ["忙","máng","bận"],
  ["猫","māo","mèo"],
  ["没关系","méi guānxi","không sao"],
  ["没事","méishì","không sao; không có việc gì"],
  ["没有","méiyǒu","không có"],
  ["妹妹","mèimei","em gái"],
  ["们","men","hậu tố số nhiều"],
  ["米饭","mǐfàn","cơm"],
  ["面包","miànbāo","bánh mì"],
  ["面条儿","miàntiáor","mì; mì sợi"],
  ["明年","míngnián","năm sau"],
  ["明天","míngtiān","ngày mai"],
  ["名字","míngzi","tên"],
  ["哪","nǎ","nào"],
  ["哪个","nǎge","cái nào"],
  ["哪里","nǎlǐ","ở đâu"],
  ["哪儿","nǎr","ở đâu"],
  ["哪些","nǎxiē","những cái nào"],
  ["那","nà","kia; đó"],
  ["那边","nàbiān","phía bên kia"],
  ["那个","nàge","cái đó"],
  ["那里","nàlǐ","ở đó"],
  ["那儿","nàr","ở đó"],
  ["那些","nàxiē","những cái đó"],
  ["男","nán","nam"],
  ["男朋友","nánpéngyou","bạn trai"],
  ["呢","ne","trợ từ"],
  ["能","néng","có thể"],
  ["你","nǐ","bạn"],
  ["你好","nǐ hǎo","xin chào"],
  ["你们","nǐmen","các bạn"],
  ["年","nián","năm"],
  ["您","nín","ngài; bạn (kính ngữ)"],
  ["牛奶","niúnǎi","sữa bò"],
  ["女","nǚ","nữ"],
  ["女儿","nǚ'ér","con gái"],
  ["女朋友","nǚpéngyou","bạn gái"],
  ["女士","nǚshì","quý cô; bà; cô"],
  ["朋友","péngyou","bạn bè"],
  ["便宜","piányi","rẻ"],
  ["漂亮","piàoliang","đẹp"],
  ["苹果","píngguǒ","quả táo"],
  ["七","qī","bảy"],
  ["起床","qǐchuáng","thức dậy"],
  ["千","qiān","nghìn"],
  ["前","qián","trước; phía trước"],
  ["钱","qián","tiền"],
  ["请","qǐng","mời; xin"],
  ["请问","qǐngwèn","xin hỏi"],
  ["去","qù","đi"],
  ["去年","qùnián","năm ngoái"],
  ["热","rè","nóng"],
  ["人","rén","người"],
  ["认识","rènshi","quen biết"],
  ["日","rì","ngày"],
  ["三","sān","ba"],
  ["商店","shāngdiàn","cửa hàng"],
  ["上","shàng","trên; lên"],
  ["上班","shàngbān","đi làm"],
  ["上课","shàngkè","lên lớp; học"],
  ["上午","shàngwǔ","buổi sáng"],
  ["上学","shàngxué","đi học"],
  ["少","shǎo","ít"],
  ["谁","shéi","ai"],
  ["什么","shénme","cái gì"],
  ["生病","shēngbìng","bị bệnh"],
  ["十","shí","mười"],
  ["时候","shíhou","lúc; thời gian"],
  ["时间","shíjiān","thời gian"],
  ["事","shì","việc; sự việc"],
  ["是","shì","là"],
  ["手机","shǒujī","điện thoại di động"],
  ["书","shū","sách"],
  ["书店","shūdiàn","hiệu sách"],
  ["水","shuǐ","nước"],
  ["水果","shuǐguǒ","trái cây"],
  ["睡","shuì","ngủ"],
  ["睡觉","shuìjiào","ngủ"],
  ["说","shuō","nói"],
  ["说话","shuōhuà","nói chuyện"],
  ["四","sì","bốn"],
  ["岁","suì","tuổi"],
  ["他","tā","anh ấy; ông ấy"],
  ["它","tā","nó"],
  ["她","tā","cô ấy; bà ấy"],
  ["他们","tāmen","họ"],
  ["它们","tāmen","chúng nó"],
  ["她们","tāmen","họ; các cô ấy"],
  ["太","tài","quá; rất"],
  ["天","tiān","ngày; trời"],
  ["天气","tiānqì","thời tiết"],
  ["听","tīng","nghe"],
  ["听见","tīngjiàn","nghe thấy"],
  ["同学","tóngxué","bạn học"],
  ["外","wài","ngoài"],
  ["外边","wàibian","bên ngoài"],
  ["玩","wán","chơi"],
  ["晚","wǎn","muộn; tối"],
  ["晚饭","wǎnfàn","bữa tối"],
  ["晚上","wǎnshang","buổi tối"],
  ["喂","wèi","alo"],
  ["问","wèn","hỏi"],
  ["问题","wèntí","câu hỏi; vấn đề"],
  ["我","wǒ","tôi"],
  ["我们","wǒmen","chúng tôi; chúng ta"],
  ["五","wǔ","năm"],
  ["午饭","wǔfàn","bữa trưa"],
  ["喜欢","xǐhuan","thích"],
  ["下","xià","dưới; xuống"],
  ["下雨","xiàyǔ","mưa"],
  ["下班","xiàbān","tan làm"],
  ["下课","xiàkè","tan học"],
  ["下午","xiàwǔ","buổi chiều"],
  ["先生","xiānsheng","ông; ngài"],
  ["现在","xiànzài","bây giờ"],
  ["想","xiǎng","muốn; nghĩ"],
  ["小","xiǎo","nhỏ"],
  ["小朋友","xiǎopéngyou","trẻ em"],
  ["小时","xiǎoshí","giờ"],
  ["小学","xiǎoxué","trường tiểu học"],
  ["小学生","xiǎoxuéshēng","học sinh tiểu học"],
  ["些","xiē","một vài; một số"],
  ["写","xiě","viết"],
  ["谢谢","xièxie","cảm ơn"],
  ["新","xīn","mới"],
  ["星期","xīngqī","tuần; thứ"],
  ["星期日","xīngqīrì","Chủ nhật"],
  ["星期天","xīngqītiān","Chủ nhật"],
  ["休息","xiūxi","nghỉ ngơi"],
  ["学","xué","học"],
  ["学生","xuéshēng","học sinh; sinh viên"],
  ["学习","xuéxí","học tập"],
  ["学校","xuéxiào","trường học"],
  ["一","yī","một"],
  ["一半","yíbàn","một nửa"],
  ["一下","yíxià","một chút"],
  ["一点儿","yìdiǎnr","một chút"],
  ["一些","yìxiē","một số; một vài"],
  ["衣服","yīfu","quần áo"],
  ["医生","yīshēng","bác sĩ"],
  ["医院","yīyuàn","bệnh viện"],
  ["椅子","yǐzi","ghế"],
  ["元","yuán","đồng; nhân dân tệ"],
  ["月","yuè","tháng; mặt trăng"],
  ["再","zài","lại; lần nữa"],
  ["再见","zàijiàn","tạm biệt"],
  ["早","zǎo","sớm"],
  ["早饭","zǎofàn","bữa sáng"],
  ["早上","zǎoshang","buổi sáng"],
  ["怎么","zěnme","thế nào; làm sao"],
  ["怎么样","zěnmeyàng","thế nào"],
  ["找","zhǎo","tìm"],
  ["这","zhè","này; đây"],
  ["这边","zhèbiān","phía này"],
  ["这个","zhège","cái này"],
  ["这里","zhèlǐ","ở đây"],
  ["这儿","zhèr","ở đây"],
  ["这些","zhèxiē","những cái này"],
  ["真","zhēn","thật; thực sự"],
  ["正在","zhèngzài","đang"],
  ["知道","zhīdào","biết"],
  ["只","zhī","chỉ; con (lượng từ)"],
  ["中国","Zhōngguó","Trung Quốc"],
  ["中文","Zhōngwén","tiếng Trung"],
  ["中午","zhōngwǔ","buổi trưa"],
  ["中学","zhōngxué","trường trung học"],
  ["中学生","zhōngxuéshēng","học sinh trung học"],
  ["住","zhù","sống; ở"],
  ["桌子","zhuōzi","cái bàn"],
  ["昨天","zuótiān","hôm qua"],
  ["坐","zuò","ngồi; đi bằng"],
  ["做","zuò","làm"],
  ["做饭","zuòfàn","nấu cơm"],
  ["雪","xuě","tuyết"],
  ["要","yào","muốn; cần; sẽ"],
  ["也","yě","cũng"],
  ["有","yǒu","có"],
  ["有的","yǒude","có cái; một số"],
  ["有点儿","yǒudiǎnr","hơi; có chút"],
  ["有些","yǒuxiē","một số; hơi"],
  ["雨","yǔ","mưa"],
  ["在","zài","ở; tại; đang"],
  ["字","zì","chữ"]
];
