window.HSK2 = [
  ["啊", "a", "à, nhé, ạ"],
  ["爱好", "àihào", "sở thích; yêu thích"],
  ["白色", "báisè", "màu trắng"],
  ["班", "bān", "lớp; ca; nhóm"],
  ["帮", "bāng", "giúp; hỗ trợ"],
  ["帮忙", "bāngmáng", "giúp đỡ"],
  ["包", "bāo", "gói; túi; bao"],
  ["本子", "běnzi", "vở; sổ; sách"],
  ["比", "bǐ", "so với; so sánh"],
  ["笔", "bǐ", "bút; nét chữ"],
  ["别1", "bié", "đừng; chớ"],
  ["不错", "búcuò", "không tệ; khá tốt; đúng"],
  ["不好意思", "bùhǎoyìsi", "ngại quá; xin lỗi"],
  ["长", "cháng", "dài"],
  ["车站", "chēzhàn", "ga; trạm xe"],
  ["出", "chū", "ra; xuất hiện"],
  ["出国", "chūguó", "ra nước ngoài"],
  ["出来", "chūlái", "đi ra; xuất hiện"],
  ["出门", "chūmén", "ra ngoài; ra khỏi nhà"],
  ["出去", "chūqù", "đi ra ngoài"],
  ["床", "chuáng", "giường"],
  ["词", "cí", "từ; từ ngữ"],
  ["次", "cì", "lần; thứ"],
  ["从", "cóng", "từ; theo"],
  ["从小", "cóngxiǎo", "từ nhỏ"],
  ["错", "cuò", "sai; lỗi"],
  ["打1", "dǎ", "đánh; làm; thực hiện"],
  ["打车", "dǎchē", "đi taxi; bắt taxi"],
  ["打开", "dǎkāi", "mở"],
  ["但", "dàn", "nhưng; chỉ"],
  ["但是", "dànshì", "nhưng; tuy nhiên"],
  ["得", "de", "trợ từ bổ ngữ"],
  ["地", "de", "trợ từ trạng ngữ"],
  ["等1", "děng", "đợi; chờ"],
  ["地铁", "dìtiě", "tàu điện ngầm"],
  ["点2", "diǎn", "chạm; gọi món; điểm"],
  ["懂", "dǒng", "hiểu"],
  ["动", "dòng", "động; di chuyển"],
  ["饭馆", "fànguǎn", "nhà hàng; quán ăn"],
  ["飞", "fēi", "bay"],
  ["高", "gāo", "cao"],
  ["高中", "gāozhōng", "trung học phổ thông"],
  ["告诉", "gàosu", "nói cho; báo cho"],
  ["个子", "gèzi", "vóc dáng; chiều cao"],
  ["跟", "gēn", "với; theo; cùng"],
  ["公交车", "gōngjiāochē", "xe buýt"],
  ["过", "guò", "đi qua; trải qua"],
  ["过来", "guòlái", "đi qua đây; đến đây"],
  ["过年", "guònián", "ăn Tết; đón năm mới"],
  ["过去1", "guòqù", "quá khứ; đi qua"],
  ["过", "guo", "đã từng; trợ từ chỉ trải nghiệm"],
  ["还是", "háishi", "vẫn; hay là; tốt hơn là"],
  ["黑色", "hēisè", "màu đen"],
  ["红茶", "hóngchá", "trà đen"],
  ["红色", "hóngsè", "màu đỏ"],
  ["后面", "hòumiàn", "phía sau; đằng sau"],
  ["花1", "huā", "tiêu (tiền/thời gian); hoa"],
  ["花2", "huā", "hoa"],
  ["画", "huà", "vẽ; tranh"],
  ["坏", "huài", "xấu; hỏng"],
  ["回来", "huílái", "quay lại; trở về"],
  ["回去", "huíqù", "quay về; trở về"],
  ["机场", "jīchǎng", "sân bay"],
  ["机票", "jīpiào", "vé máy bay"],
  ["记得", "jìde", "nhớ"],
  ["间", "jiān", "gian; phòng; khoảng"],
  ["教", "jiāo", "dạy"],
  ["教室", "jiàoshì", "phòng học; lớp học"],
  ["介绍", "jièshào", "giới thiệu"],
  ["进", "jìn", "vào; tiến vào"],
  ["近", "jìn", "gần"],
  ["进来", "jìnlái", "đi vào đây"],
  ["进去", "jìnqù", "đi vào"],
  ["经常", "jīngcháng", "thường xuyên"],
  ["酒店", "jiǔdiàn", "khách sạn; quán rượu"],
  ["就", "jiù", "thì; liền; chỉ; chính là"],
  ["咖啡", "kāfēi", "cà phê"],
  ["开始", "kāishǐ", "bắt đầu"],
  ["开学", "kāixué", "khai giảng; bắt đầu học kỳ"],
  ["考", "kǎo", "thi; kiểm tra"],
  ["考试", "kǎoshì", "thi; kỳ thi"],
  ["可能", "kěnéng", "có thể; khả năng"],
  ["裤子", "kùzi", "quần"],
  ["快", "kuài", "nhanh; sắp"],
  ["快乐", "kuàilè", "vui vẻ; vui"],
  ["快要", "kuàiyào", "sắp; gần như"],
  ["篮球", "lánqiú", "bóng rổ"],
  ["累", "lèi", "mệt"],
  ["离", "lí", "cách; rời khỏi"],
  ["里面", "lǐmiàn", "bên trong"],
  ["楼", "lóu", "tòa nhà; tầng"],
  ["路", "lù", "đường"],
  ["路上", "lùshang", "trên đường"],
  ["旅游", "lǚyóu", "du lịch"],
  ["绿茶", "lǜchá", "trà xanh"],
  ["绿色", "lǜsè", "màu xanh lá"],
  ["慢", "màn", "chậm"],
  ["没意思", "méiyìsi", "vô vị; chán"],
  ["每", "měi", "mỗi; mỗi một"],
  ["门", "mén", "cửa; cổng"],
  ["门口", "ménkǒu", "cửa ra vào; trước cửa"],
  ["门票", "ménpiào", "vé vào cửa"],
  ["面", "miàn", "mặt; phía; bề mặt"],
  ["名", "míng", "tên; danh; người"],
  ["拿", "ná", "cầm; lấy"],
  ["那么", "nàme", "như vậy; thế; vậy thì"],
  ["那样", "nàyàng", "như thế; kiểu đó"],
  ["奶茶", "nǎichá", "trà sữa"],
  ["奶奶", "nǎinai", "bà nội"],
  ["男孩儿", "nánháir", "bé trai; con trai"],
  ["鸟", "niǎo", "chim"],
  ["女孩儿", "nǚháir", "bé gái; con gái"],
  ["旁边", "pángbiān", "bên cạnh"],
  ["跑", "pǎo", "chạy"],
  ["跑步", "pǎobù", "chạy bộ"],
  ["票", "piào", "vé; phiếu"],
  ["妻子", "qīzi", "vợ"],
  ["起来", "qǐlái", "đứng dậy; thức dậy"],
  ["前面", "qiánmiàn", "phía trước"],
  ["晴", "qíng", "trời quang; nắng đẹp"],
  ["球", "qiú", "quả bóng; bóng"],
  ["让", "ràng", "để; cho phép; nhường"],
  ["肉", "ròu", "thịt"],
  ["商场", "shāngchǎng", "trung tâm thương mại"],
  ["上来", "shànglái", "đi lên đây"],
  ["上面", "shàngmiàn", "phía trên; bên trên"],
  ["上去", "shàngqù", "đi lên"],
  ["上网", "shàngwǎng", "lên mạng; truy cập Internet"],
  ["身体", "shēntǐ", "cơ thể; sức khỏe"],
  ["生日", "shēngrì", "sinh nhật"],
  ["时", "shí", "giờ; thời gian"],
  ["事情", "shìqing", "việc; sự việc"],
  ["手", "shǒu", "tay"],
  ["手表", "shǒubiǎo", "đồng hồ đeo tay"],
  ["书包", "shūbāo", "cặp sách; ba lô sách"],
  ["舒服", "shūfu", "thoải mái; dễ chịu"],
  ["送", "sòng", "tặng; đưa; tiễn"],
  ["虽然", "suīrán", "mặc dù"],
  ["所以", "suǒyǐ", "cho nên; vì vậy"],
  ["疼", "téng", "đau"],
  ["踢", "tī", "đá"],
  ["题", "tí", "đề; câu hỏi; bài tập"],
  ["条", "tiáo", "cái; chiếc; lượng từ vật dài"],
  ["跳舞", "tiàowǔ", "nhảy múa"],
  ["头", "tóu", "đầu"],
  ["外国", "wàiguó", "nước ngoài"],
  ["外面", "wàimiàn", "bên ngoài"],
  ["完", "wán", "xong; hoàn thành"],
  ["万", "wàn", "mười nghìn; vạn"],
  ["往", "wǎng", "hướng về; đi về"],
  ["网上", "wǎngshang", "trên mạng"],
  ["忘", "wàng", "quên"],
  ["位", "wèi", "vị; người (cách nói lịch sự)"],
  ["为什么", "wèishénme", "tại sao; vì sao"],
  ["希望", "xīwàng", "hy vọng"],
  ["洗", "xǐ", "rửa; giặt"],
  ["洗手间", "xǐshǒujiān", "nhà vệ sinh"],
  ["下来", "xiàlái", "đi xuống đây"],
  ["下面", "xiàmiàn", "phía dưới; bên dưới"],
  ["下去", "xiàqù", "đi xuống"],
  ["小孩儿", "xiǎoháir", "trẻ con"],
  ["小时候", "xiǎoshíhou", "hồi nhỏ; thời thơ ấu"],
  ["笑", "xiào", "cười"],
  ["姓", "xìng", "họ; mang họ"],
  ["姓名", "xìngmíng", "họ tên; tên đầy đủ"],
  ["颜色", "yánsè", "màu sắc"],
  ["眼睛", "yǎnjing", "mắt"],
  ["药", "yào", "thuốc"],
  ["药店", "yàodiàn", "hiệu thuốc; nhà thuốc"],
  ["爷爷", "yéye", "ông nội"],
  ["一会儿", "yíhuìr", "một lát; một lúc"],
  ["已经", "yǐjīng", "đã; đã rồi"],
  ["一起", "yìqǐ", "cùng nhau"],
  ["意思", "yìsi", "ý nghĩa; ý; ý muốn"],
  ["阴", "yīn", "âm u; nhiều mây"],
  ["因为", "yīnwèi", "bởi vì; vì"],
  ["游", "yóu", "bơi; đi chơi; du ngoạn"],
  ["游泳", "yóuyǒng", "bơi; bơi lội"],
  ["有意思", "yǒuyìsi", "thú vị; có ý nghĩa"],
  ["有时", "yǒushí", "đôi khi; có lúc"],
  ["右", "yòu", "bên phải"],
  ["右边", "yòubian", "bên phải"],
  ["鱼", "yú", "cá"],
  ["远", "yuǎn", "xa"],
  ["运动", "yùndòng", "vận động; thể thao"],
  ["站1", "zhàn", "trạm; nhà ga"],
  ["丈夫", "zhàngfu", "chồng"],
  ["这么", "zhème", "như thế này; như vậy"],
  ["这样", "zhèyàng", "như thế này; như vậy"],
  ["着", "zhe", "đang; trợ từ chỉ trạng thái"],
  ["正", "zhèng", "đang; chính; đúng"],
  ["周", "zhōu", "tuần"],
  ["准备", "zhǔnbèi", "chuẩn bị"],
  ["自己", "zìjǐ", "bản thân; chính mình"],
  ["走", "zǒu", "đi; đi bộ; rời đi"],
  ["走路", "zǒulù", "đi bộ"],
  ["足球", "zúqiú", "bóng đá"],
  ["最", "zuì", "nhất"],
  ["左", "zuǒ", "bên trái"],
  ["左边", "zuǒbian", "bên trái"]
];
