window.HSK3 = [
  ["阿姨", "āyí", "cô, dì, bác gái"],
  ["矮", "ǎi", "thấp, lùn"],
  ["爱人", "àiren", "vợ/chồng, người bạn đời"],
  ["安静", "ānjìng", "yên tĩnh, yên lặng"],
  ["安全", "ānquán", "an toàn"],
  ["把", "bǎ", "cầm, lấy; giới từ 把; lượng từ"],
  ["搬", "bān", "chuyển, dọn, bê"],
  ["班级", "bānjí", "lớp học"],
  ["搬家", "bānjiā", "chuyển nhà"],
  ["办", "bàn", "làm, xử lý, giải quyết"],
  ["办法", "bànfǎ", "cách, biện pháp"],
  ["办公室", "bàngōngshì", "văn phòng"],
  ["半天", "bàntiān", "nửa ngày; khá lâu"],
  ["帮助", "bāngzhù", "giúp đỡ; sự giúp đỡ"],
  ["饱", "bǎo", "no"],
  ["报纸", "bàozhǐ", "báo"],
  ["北", "běi", "phía bắc"],
  ["北方", "běifāng", "miền Bắc, phía Bắc"],
  ["被", "bèi", "bị; được; giới từ bị động"],
  ["笔记", "bǐjì", "ghi chép, ghi chú"],
  ["比较", "bǐjiào", "so sánh; tương đối"],
  ["笔记本", "bǐjìběn", "vở ghi chép; máy tính xách tay"],
  ["比如", "bǐrú", "ví dụ như"],
  ["比赛", "bǐsài", "thi đấu; cuộc thi"],
  ["必须", "bìxū", "phải, nhất định phải"],
  ["变", "biàn", "thay đổi, biến thành"],
  ["遍", "biàn", "lần, lượt; lượt từ đầu đến cuối"],
  ["变成", "biànchéng", "biến thành, trở thành"],
  ["变化", "biànhuà", "thay đổi; sự thay đổi"],
  ["表演", "biǎoyǎn", "biểu diễn; tiết mục"],
  ["别的", "biéde", "khác, cái khác"],
  ["别人", "biérén", "người khác"],
  ["宾馆", "bīnguǎn", "khách sạn"],
  ["冰", "bīng", "băng, đá"],
  ["冰激凌", "bīngjīlíng", "kem"],
  ["冰箱", "bīngxiāng", "tủ lạnh"],
  ["病人", "bìngrén", "bệnh nhân"],
  ["不但", "búdàn", "không những, không chỉ"],
  ["不见", "bújiàn", "không thấy; biến mất"],
  ["不用", "búyòng", "không cần"],
  ["不同", "bùtóng", "khác nhau"],
  ["不久", "bùjiǔ", "không lâu; chẳng bao lâu"],
  ["不行", "bùxíng", "không được; không ổn"],
  ["才1", "cái", "mới; mãi đến"],
  ["菜单", "càidān", "thực đơn"],
  ["参加", "cānjiā", "tham gia"],
  ["草", "cǎo", "cỏ"],
  ["草地", "cǎodì", "bãi cỏ"],
  ["层", "céng", "tầng; lớp"],
  ["查", "chá", "tra, kiểm tra, tìm kiếm"],
  ["差", "chà", "kém; sai; khác"],
  ["差不多", "chàbuduō", "gần như; xấp xỉ; tương đối"],
  ["尝", "cháng", "nếm, thử"],
  ["常", "cháng", "thường, thường xuyên"],
  ["常见", "chángjiàn", "thường gặp, phổ biến"],
  ["常用", "chángyòng", "thường dùng"],
  ["常常", "chángcháng", "thường xuyên"],
  ["衬衫", "chènshān", "áo sơ mi"],
  ["成绩", "chéngjì", "thành tích; điểm số"],
  ["城市", "chéngshì", "thành phố"],
  ["迟到", "chídào", "đến muộn"],
  ["出发", "chūfā", "xuất phát"],
  ["出生", "chūshēng", "sinh ra"],
  ["出院", "chūyuàn", "xuất viện"],
  ["初中", "chūzhōng", "trung học cơ sở"],
  ["除了", "chúle", "ngoài; ngoại trừ"],
  ["船", "chuán", "thuyền, tàu"],
  ["春天", "chūntiān", "mùa xuân"],
  ["词典", "cídiǎn", "từ điển"],
  ["聪明", "cōngmíng", "thông minh"],
  ["打扫", "dǎsǎo", "quét dọn, vệ sinh"],
  ["打算", "dǎsuàn", "dự định, dự tính"],
  ["大概", "dàgài", "đại khái; khoảng; có lẽ"],
  ["大人", "dàren", "người lớn"],
  ["大小", "dàxiǎo", "kích thước; lớn nhỏ"],
  ["大熊猫", "dàxióngmāo", "gấu trúc"],
  ["大衣", "dàyī", "áo khoác dài"],
  ["带", "dài", "mang, đem, dẫn"],
  ["担心", "dānxīn", "lo lắng"],
  ["蛋糕", "dàngāo", "bánh ngọt, bánh kem"],
  ["当然", "dāngrán", "đương nhiên, tất nhiên"],
  ["到处", "dàochù", "khắp nơi"],
  ["得到", "dédào", "nhận được, đạt được"],
  ["得分", "défēn", "ghi điểm; điểm số"],
  ["的话", "dehuà", "nếu; nếu mà"],
  ["得", "děi", "phải, cần phải"],
  ["灯", "dēng", "đèn"],
  ["地", "dì", "mặt đất; nơi"],
  ["地点", "dìdiǎn", "địa điểm"],
  ["地方", "dìfang", "nơi, địa phương"],
  ["地图", "dìtú", "bản đồ"],
  ["电", "diàn", "điện"],
  ["电梯", "diàntī", "thang máy"],
  ["电子书", "diànzǐshū", "sách điện tử"],
  ["丢", "diū", "mất; vứt"],
  ["东", "dōng", "phía đông"],
  ["东北", "dōngběi", "Đông Bắc"],
  ["东方", "dōngfāng", "phía đông; phương Đông"],
  ["东南", "dōngnán", "Đông Nam"],
  ["冬天", "dōngtiān", "mùa đông"],
  ["懂得", "dǒngde", "hiểu, biết"],
  ["动物", "dòngwù", "động vật"],
  ["动物园", "dòngwùyuán", "vườn thú"],
  ["短", "duǎn", "ngắn"],
  ["短裤", "duǎnkù", "quần đùi, quần short"],
  ["段", "duàn", "đoạn; khoảng; lượng từ"],
  ["锻炼", "duànliàn", "rèn luyện, tập thể dục"],
  ["对话", "duìhuà", "đối thoại; nói chuyện"],
  ["饿", "è", "đói"],
  ["而且", "érqiě", "hơn nữa, vả lại"],
  ["耳朵", "ěrduo", "tai"],
  ["耳机", "ěrjī", "tai nghe"],
  ["发", "fā", "gửi; phát; đưa ra"],
  ["发烧", "fāshāo", "sốt"],
  ["发生", "fāshēng", "xảy ra"],
  ["发现", "fāxiàn", "phát hiện"],
  ["发展", "fāzhǎn", "phát triển"],
  ["方便", "fāngbiàn", "thuận tiện, tiện lợi"],
  ["方便面", "fāngbiànmiàn", "mì ăn liền"],
  ["方法", "fāngfǎ", "phương pháp, cách"],
  ["方向", "fāngxiàng", "phương hướng"],
  ["房子", "fángzi", "nhà"],
  ["放", "fàng", "đặt, để, thả"],
  ["放假", "fàngjià", "nghỉ lễ, nghỉ học"],
  ["放心", "fàngxīn", "yên tâm"],
  ["放学", "fàngxué", "tan học"],
  ["分开", "fēnkāi", "tách ra, chia ra"],
  ["风", "fēng", "gió"],
  ["封", "fēng", "phong; lượng từ thư"],
  ["夫妻", "fūqī", "vợ chồng"],
  ["服务", "fúwù", "phục vụ; dịch vụ"],
  ["附近", "fùjìn", "gần, khu vực lân cận"],
  ["复习", "fùxí", "ôn tập"],
  ["该1", "gāi", "nên, cần phải"],
  ["干净", "gānjìng", "sạch sẽ"],
  ["感兴趣", "gǎnxìngqù", "có hứng thú"],
  ["感到", "gǎndào", "cảm thấy"],
  ["感冒", "gǎnmào", "cảm cúm; bị cảm"],
  ["干", "gàn", "làm; công việc"],
  ["刚", "gāng", "vừa mới; vừa đúng"],
  ["刚才", "gāngcái", "vừa nãy"],
  ["刚刚", "gānggāng", "vừa mới"],
  ["高铁", "gāotiě", "tàu cao tốc"],
  ["根据", "gēnjù", "căn cứ vào; theo"],
  ["更", "gèng", "hơn; càng"],
  ["公斤", "gōngjīn", "kilôgam"],
  ["公园", "gōngyuán", "công viên"],
  ["工作日", "gōngzuòrì", "ngày làm việc"],
  ["故事", "gùshi", "câu chuyện"],
  ["刮", "guā", "thổi; cạo; gió thổi"],
  ["关", "guān", "đóng; tắt"],
  ["关机", "guānjī", "tắt máy"],
  ["关系", "guānxì", "quan hệ; liên quan"],
  ["关心", "guānxīn", "quan tâm"],
  ["关于", "guānyú", "về; liên quan đến"],
  ["关注", "guānzhù", "quan tâm; chú ý theo dõi"],
  ["国家", "guójiā", "đất nước, quốc gia"],
  ["过节", "guòjié", "đón lễ, ăn lễ"],
  ["过去2", "guòqù", "quá khứ; trước đây"],
  ["海", "hǎi", "biển"],
  ["害怕", "hàipà", "sợ, sợ hãi"],
  ["好多", "hǎoduō", "rất nhiều"],
  ["好久", "hǎojiǔ", "lâu, khá lâu"],
  ["好像", "hǎoxiàng", "hình như, giống như"],
  ["号码", "hàomǎ", "số"],
  ["河", "hé", "sông"],
  ["合适", "héshì", "phù hợp, thích hợp"],
  ["黑板", "hēibǎn", "bảng đen"],
  ["红绿灯", "hóng-lǜdēng", "đèn giao thông"],
  ["后来", "hòulái", "sau đó, về sau"],
  ["后年", "hòunián", "năm kia nữa, năm sau nữa"],
  ["后天", "hòutiān", "ngày kia"],
  ["护照", "hùzhào", "hộ chiếu"],
  ["花园", "huāyuán", "vườn hoa, vườn"],
  ["画家", "huàjiā", "họa sĩ"],
  ["欢迎", "huānyíng", "hoan nghênh, chào đón"],
  ["还", "huán", "trả lại, hoàn lại"],
  ["环境", "huánjìng", "môi trường"],
  ["换", "huàn", "đổi, thay"],
  ["黄色", "huángsè", "màu vàng"],
  ["回答", "huídá", "trả lời"],
  ["会", "huì", "cuộc họp; hội"],
  ["会议", "huìyì", "cuộc họp, hội nghị"],
  ["或", "huò", "hoặc; có lẽ"],
  ["或者", "huòzhě", "hoặc; hay là"],
  ["鸡", "jī", "gà"],
  ["几乎", "jīhū", "gần như"],
  ["机会", "jīhuì", "cơ hội"],
  ["极", "jí", "cực kỳ, vô cùng"],
  ["急", "jí", "gấp, vội; lo lắng"],
  ["记", "jì", "ghi nhớ; ghi chép"],
  ["季", "jì", "mùa"],
  ["季节", "jìjié", "mùa"],
  ["加", "jiā", "thêm; cộng; gia nhập"],
  ["假期", "jiàqī", "kỳ nghỉ"],
  ["坚持", "jiānchí", "kiên trì"],
  ["检查", "jiǎnchá", "kiểm tra"],
  ["简单", "jiǎndān", "đơn giản"],
  ["检票", "jiǎnpiào", "kiểm vé"],
  ["健康", "jiànkāng", "sức khỏe; khỏe mạnh"],
  ["见面", "jiànmiàn", "gặp mặt"],
  ["讲", "jiǎng", "nói; giảng; giải thích"],
  ["角", "jiǎo", "góc; hào"],
  ["脚", "jiǎo", "chân"],
  ["接", "jiē", "đón; nhận; tiếp"],
  ["街", "jiē", "đường phố"],
  ["节", "jié", "lễ; tiết; đoạn"],
  ["结婚", "jiéhūn", "kết hôn"],
  ["节目", "jiémù", "chương trình; tiết mục"],
  ["节日", "jiérì", "ngày lễ"],
  ["结束", "jiéshù", "kết thúc"],
  ["解决", "jiějué", "giải quyết"],
  ["姐妹", "jiěmèi", "chị em gái; anh chị em"],
  ["借", "jiè", "mượn; cho mượn"],
  ["斤", "jīn", "cân Trung Quốc"],
  ["经过", "jīngguò", "đi qua; trải qua"],
  ["经理", "jīnglǐ", "quản lý, giám đốc"],
  ["久", "jiǔ", "lâu"],
  ["酒", "jiǔ", "rượu"],
  ["旧", "jiù", "cũ"],
  ["句", "jù", "câu; lượng từ câu"],
  ["句子", "jùzi", "câu"],
  ["决定", "juédìng", "quyết định"],
  ["卡", "kǎ", "thẻ; kẹt"],
  ["开花", "kāihuā", "nở hoa"],
  ["开会", "kāihuì", "họp; tổ chức cuộc họp"],
  ["开机", "kāijī", "bật máy; khởi động máy"],
  ["开心", "kāixīn", "vui vẻ"],
  ["看来", "kànlái", "xem ra, có vẻ"],
  ["可", "kě", "có thể; nhưng"],
  ["渴", "kě", "khát"],
  ["可爱", "kě'ài", "đáng yêu"],
  ["可是", "kěshì", "nhưng, tuy nhiên"],
  ["刻", "kè", "khắc; 15 phút"],
  ["课本", "kèběn", "sách giáo khoa"],
  ["客人", "kèrén", "khách"],
  ["课文", "kèwén", "bài khóa"],
  ["空调", "kōngtiáo", "điều hòa"],
  ["哭", "kū", "khóc"],
  ["筷子", "kuàizi", "đũa"],
  ["矿泉水", "kuàngquánshuǐ", "nước khoáng"],
  ["来自", "láizì", "đến từ"],
  ["蓝", "lán", "màu xanh lam"],
  ["老", "lǎo", "già; cũ; lâu năm"],
  ["老人", "lǎorén", "người già"],
  ["离开", "líkāi", "rời khỏi"],
  ["礼物", "lǐwù", "quà, lễ vật"],
  ["历史", "lìshǐ", "lịch sử"],
  ["脸", "liǎn", "mặt"],
  ["练", "liàn", "luyện tập"],
  ["练习", "liànxí", "luyện tập; bài tập"],
  ["凉快", "liángkuai", "mát mẻ"],
  ["辆", "liàng", "lượng từ xe cộ"],
  ["聊", "liáo", "trò chuyện"],
  ["聊天儿", "liáotiānr", "nói chuyện, tán gẫu"],
  ["了解", "liǎojiě", "hiểu; tìm hiểu"],
  ["邻居", "línjū", "hàng xóm"],
  ["留学", "liúxué", "du học"],
  ["留学生", "liúxuéshēng", "du học sinh"],
  ["楼梯", "lóutī", "cầu thang"],
  ["路边", "lùbiān", "ven đường"],
  ["路口", "lùkǒu", "ngã đường, giao lộ"],
  ["马", "mǎ", "ngựa"],
  ["马路", "mǎlù", "đường phố"],
  ["马上", "mǎshàng", "ngay lập tức"],
  ["满意", "mǎnyì", "hài lòng"],
  ["毛", "máo", "mao; một phần mười nhân dân tệ"],
  ["米", "mǐ", "gạo; mét"],
  ["面前", "miànqián", "phía trước; trước mặt"],
  ["明白", "míngbai", "hiểu; rõ ràng"],
  ["名单", "míngdān", "danh sách"],
  ["名人", "míngrén", "người nổi tiếng"],
  ["南", "nán", "phía nam"],
  ["难", "nán", "khó; tai nạn, khổ nạn"],
  ["南方", "nánfāng", "phía Nam"],
  ["难过", "nánguò", "buồn; khó chịu"],
  ["难看", "nánkàn", "xấu; khó coi"],
  ["男人", "nánrén", "đàn ông"],
  ["男生", "nánshēng", "nam sinh, con trai"],
  ["难题", "nántí", "vấn đề khó"],
  ["难听", "nántīng", "khó nghe"],
  ["年级", "niánjí", "khối lớp"],
  ["年轻", "niánqīng", "trẻ"],
  ["牛", "niú", "bò"],
  ["努力", "nǔlì", "nỗ lực; chăm chỉ"],
  ["女人", "nǚrén", "phụ nữ"],
  ["女生", "nǚshēng", "nữ sinh, con gái"],
  ["爬", "pá", "leo; bò"],
  ["怕", "pà", "sợ"],
  ["拍照", "pāizhào", "chụp ảnh"],
  ["盘子", "pánzi", "đĩa"],
  ["胖", "pàng", "béo, mập"],
  ["啤酒", "píjiǔ", "bia"],
  ["平时", "píngshí", "thường ngày"],
  ["瓶子", "píngzi", "chai, lọ"],
  ["骑", "qí", "cưỡi; đi xe"],
  ["奇怪", "qíguài", "kỳ lạ"],
  ["其实", "qíshí", "thực ra"],
  ["其他", "qítā", "khác; những cái khác"],
  ["起", "qǐ", "đứng dậy; bắt đầu; lượng từ sự việc"],
  ["起飞", "qǐfēi", "cất cánh"],
  ["汽车", "qìchē", "ô tô, xe hơi"],
  ["铅笔", "qiānbǐ", "bút chì"],
  ["前年", "qiánnián", "năm kia"],
  ["前天", "qiántiān", "hôm kia"],
  ["清楚", "qīngchu", "rõ; hiểu rõ"],
  ["请假", "qǐngjià", "xin nghỉ"],
  ["请客", "qǐngkè", "mời khách; đãi khách"],
  ["秋天", "qiūtiān", "mùa thu"],
  ["球场", "qiúchǎng", "sân bóng; sân thể thao"],
  ["裙子", "qúnzi", "váy"],
  ["然后", "ránhòu", "sau đó"],
  ["热情", "rèqíng", "nhiệt tình"],
  ["认得", "rènde", "nhận ra; biết"],
  ["认为", "rènwéi", "cho rằng"],
  ["认真", "rènzhēn", "nghiêm túc; chăm chỉ"],
  ["容易", "róngyì", "dễ"],
  ["如果", "rúguǒ", "nếu"],
  ["伞", "sǎn", "ô, dù"],
  ["扫", "sǎo", "quét"],
  ["沙发", "shāfā", "ghế sofa"],
  ["山", "shān", "núi"],
  ["上衣", "shàngyī", "áo; áo ngoài"],
  ["勺子", "sháozi", "thìa"],
  ["身边", "shēnbiān", "bên cạnh; bên mình"],
  ["身高", "shēngāo", "chiều cao"],
  ["声", "shēng", "âm thanh; tiếng"],
  ["生活", "shēnghuó", "cuộc sống; sinh sống"],
  ["生气", "shēngqì", "tức giận"],
  ["声音", "shēngyīn", "âm thanh, tiếng nói"],
  ["市", "shì", "thành phố; chợ"],
  ["试", "shì", "thử; kiểm tra"],
  ["室", "shì", "phòng"],
  ["世界", "shìjiè", "thế giới"],
  ["收", "shōu", "nhận; thu; cất"],
  ["收到", "shōudào", "nhận được"],
  ["受", "shòu", "nhận; chịu"],
  ["瘦", "shòu", "gầy"],
  ["受到", "shòudào", "nhận được; chịu"],
  ["叔叔", "shūshu", "chú; bác trai"],
  ["树", "shù", "cây"],
  ["数学", "shùxué", "toán học"],
  ["刷", "shuā", "chải; quét"],
  ["双", "shuāng", "đôi; cặp"],
  ["水平", "shuǐpíng", "trình độ; mức độ"],
  ["司机", "sījī", "tài xế"],
  ["四季", "sìjì", "bốn mùa"],
  ["太阳", "tàiyáng", "mặt trời"],
  ["糖", "táng", "đường; kẹo"],
  ["特别", "tèbié", "đặc biệt; rất"],
  ["提高", "tígāo", "nâng cao"],
  ["体育", "tǐyù", "thể thao; giáo dục thể chất"],
  ["体育馆", "tǐyùguǎn", "nhà thi đấu; sân vận động"],
  ["甜", "tián", "ngọt"],
  ["跳", "tiào", "nhảy"],
  ["听说", "tīngshuō", "nghe nói"],
  ["挺", "tǐng", "khá; rất"],
  ["同事", "tóngshì", "đồng nghiệp"],
  ["同意", "tóngyì", "đồng ý"],
  ["头发", "tóufa", "tóc"],
  ["突然", "tūrán", "đột nhiên"],
  ["图书馆", "túshūguǎn", "thư viện"],
  ["腿", "tuǐ", "chân"],
  ["外地", "wàidì", "nơi khác; ngoại tỉnh"],
  ["外卖", "wàimài", "đồ ăn mang về; giao đồ ăn"],
  ["外语", "wàiyǔ", "ngoại ngữ"],
  ["完成", "wánchéng", "hoàn thành"],
  ["碗", "wǎn", "bát"],
  ["晚点", "wǎndiǎn", "trễ; muộn"],
  ["晚会", "wǎnhuì", "tiệc tối; chương trình buổi tối"],
  ["网球", "wǎngqiú", "quần vợt; tennis"],
  ["网站", "wǎngzhàn", "trang web"],
  ["忘记", "wàngjì", "quên"],
  ["为", "wèi", "vì; cho; đối với"],
  ["为了", "wèile", "để; vì mục đích"],
  ["卫生间", "wèishēngjiān", "nhà vệ sinh"],
  ["文化", "wénhuà", "văn hóa"],
  ["屋子", "wūzi", "nhà; căn phòng"],
  ["西", "xī", "phía tây"],
  ["西北", "xīběi", "Tây Bắc"],
  ["西方", "xīfāng", "phương Tây"],
  ["西瓜", "xīguā", "dưa hấu"],
  ["西南", "xīnán", "Tây Nam"],
  ["习惯", "xíguàn", "thói quen; quen"],
  ["喜爱", "xǐ'ài", "yêu thích"],
  ["洗衣机", "xǐyījī", "máy giặt"],
  ["洗澡", "xǐzǎo", "tắm"],
  ["夏天", "xiàtiān", "mùa hè"],
  ["先", "xiān", "trước; đầu tiên"],
  ["香蕉", "xiāngjiāo", "chuối"],
  ["相信", "xiāngxìn", "tin tưởng"],
  ["箱子", "xiāngzi", "vali; hòm; hộp"],
  ["向", "xiàng", "hướng về; đối với"],
  ["像", "xiàng", "giống; giống như"],
  ["相机", "xiàngjī", "máy ảnh"],
  ["小区", "xiǎoqū", "khu dân cư"],
  ["小心", "xiǎoxīn", "cẩn thận"],
  ["校园", "xiàoyuán", "khuôn viên trường"],
  ["校长", "xiàozhǎng", "hiệu trưởng"],
  ["鞋", "xié", "giày"],
  ["心里", "xīnlǐ", "trong lòng; trong tâm trí"],
  ["新年", "xīnnián", "năm mới"],
  ["新闻", "xīnwén", "tin tức"],
  ["新鲜", "xīnxiān", "tươi; mới mẻ"],
  ["信", "xìn", "thư; tin tưởng"],
  ["信用卡", "xìnyòngkǎ", "thẻ tín dụng"],
  ["行", "xíng", "đi; được; có thể"],
  ["行李", "xíngli", "hành lý"],
  ["兴趣", "xìngqù", "hứng thú; sở thích"],
  ["休假", "xiūjià", "nghỉ phép"],
  ["需要", "xūyào", "cần; cần thiết"],
  ["选", "xuǎn", "chọn"],
  ["选择", "xuǎnzé", "lựa chọn"],
  ["学期", "xuéqī", "học kỳ"],
  ["牙", "yá", "răng"],
  ["牙刷", "yáshuā", "bàn chải đánh răng"],
  ["羊", "yáng", "cừu; dê"],
  ["养", "yǎng", "nuôi; dưỡng"],
  ["要求", "yāoqiú", "yêu cầu"],
  ["页", "yè", "trang"],
  ["一定", "yídìng", "nhất định; chắc chắn"],
  ["一共", "yígòng", "tổng cộng"],
  ["一块儿", "yíkuàir", "cùng nhau"],
  ["一样", "yíyàng", "giống nhau"],
  ["以后", "yǐhòu", "sau này; sau đó"],
  ["以前", "yǐqián", "trước đây"],
  ["以上", "yǐshàng", "trở lên; trên"],
  ["以外", "yǐwài", "ngoài; ngoại trừ"],
  ["以为", "yǐwéi", "cứ tưởng rằng; cho rằng"],
  ["以下", "yǐxià", "trở xuống; dưới"],
  ["一般", "yìbān", "bình thường; nói chung"],
  ["一边", "yìbiān", "một bên; vừa... vừa..."],
  ["一直", "yìzhí", "luôn luôn; liên tục"],
  ["音乐", "yīnyuè", "âm nhạc"],
  ["银行", "yínháng", "ngân hàng"],
  ["银行卡", "yínhángkǎ", "thẻ ngân hàng"],
  ["饮料", "yǐnliào", "đồ uống"],
  ["应该", "yīnggāi", "nên; phải"],
  ["影响", "yǐngxiǎng", "ảnh hưởng"],
  ["用", "yòng", "dùng, sử dụng"],
  ["邮件", "yóujiàn", "thư; email"],
  ["游客", "yóukè", "du khách"],
  ["游戏", "yóuxì", "trò chơi; chơi"],
  ["邮箱", "yóuxiāng", "hộp thư; email"],
  ["有关", "yǒuguān", "liên quan đến"],
  ["有名", "yǒumíng", "nổi tiếng"],
  ["有用", "yǒuyòng", "có ích"],
  ["又", "yòu", "lại; cũng"],
  ["羽毛球", "yǔmáoqiú", "cầu lông"],
  ["语言", "yǔyán", "ngôn ngữ"],
  ["雨衣", "yǔyī", "áo mưa"],
  ["遇到", "yùdào", "gặp phải; gặp"],
  ["遇见", "yùjiàn", "gặp"],
  ["园", "yuán", "vườn; khu vui chơi"],
  ["员", "yuán", "người; nhân viên; thành viên"],
  ["愿意", "yuànyì", "sẵn lòng; muốn"],
  ["越", "yuè", "vượt; càng... càng..."],
  ["月亮", "yuèliang", "mặt trăng"],
  ["运动会", "yùndònghuì", "hội thao"],
  ["运动员", "yùndòngyuán", "vận động viên"],
  ["咱们", "zánmen", "chúng ta, chúng mình"],
  ["脏", "zāng", "bẩn"],
  ["怎么办", "zěnmebàn", "làm thế nào; phải làm sao"],
  ["怎样", "zěnyàng", "thế nào"],
  ["站2", "zhàn", "đứng"],
  ["张", "zhāng", "mở rộng; lượng từ vật phẳng"],
  ["长", "zhǎng", "lớn lên; trưởng; phát triển"],
  ["着急", "zháojí", "lo lắng; sốt ruột"],
  ["照", "zhào", "theo; chiếu; chụp"],
  ["照顾", "zhàogù", "chăm sóc"],
  ["照片", "zhàopiàn", "ảnh; bức ảnh"],
  ["照相", "zhàoxiàng", "chụp ảnh"],
  ["直到", "zhídào", "cho đến"],
  ["只", "zhǐ", "chỉ"],
  ["纸", "zhǐ", "giấy"],
  ["只能", "zhǐnéng", "chỉ có thể"],
  ["只是", "zhǐshì", "chỉ là; chỉ"],
  ["只要", "zhǐyào", "chỉ cần"],
  ["只有", "zhǐyǒu", "chỉ có; chỉ khi"],
  ["中", "zhōng", "trong; giữa"],
  ["中间", "zhōngjiān", "ở giữa"],
  ["终于", "zhōngyú", "cuối cùng"],
  ["种", "zhǒng", "loại; chủng; lượng từ loại"],
  ["重要", "zhòngyào", "quan trọng"],
  ["周末", "zhōumò", "cuối tuần"],
  ["主要", "zhǔyào", "chủ yếu; chính"],
  ["注意", "zhùyì", "chú ý"],
  ["住院", "zhùyuàn", "nhập viện; nằm viện"],
  ["字典", "zìdiǎn", "từ điển"],
  ["自行车", "zìxíngchē", "xe đạp"],
  ["子", "zi", "hậu tố danh từ"],
  ["总", "zǒng", "luôn; tổng; nói chung"],
  ["总是", "zǒngshì", "luôn luôn"],
  ["嘴", "zuǐ", "miệng"],
  ["最好", "zuìhǎo", "tốt nhất; tốt hơn hết"],
  ["最后", "zuìhòu", "cuối cùng; sau cùng"],
  ["最近", "zuìjìn", "gần đây; gần nhất"],
  ["做客", "zuòkè", "làm khách; đến chơi"],
  ["作业", "zuòyè", "bài tập; công việc"]
];
